fix syntax error

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -70,14 +70,13 @@ jobs:
         run: |
           sudo nohup openvpn --config ~/openvpn-config.ovpn --auth-nocache --askpass ~/openvpn.txt > /dev/null 2>&1 &
 
-          - name: Wait for VPN Connection
-          run: |
-            timeout 120s bash -c '
-              while ! pgrep -x "openvpn" > /dev/null; do sleep 1; done
-            ' || { echo "VPN connection timed out"; exit 1; }
-
-            echo "VPN connected. Checking interface IP..."
-            ifconfig tun0 || { echo "Interface tun0 not found"; exit 1; }
+      - name: Wait for VPN Connection
+        run: |
+          timeout 120s bash -c '
+            while ! pgrep -x "openvpn" > /dev/null; do sleep 1; done
+          ' || { echo "VPN connection timed out"; exit 1; }
+          echo "VPN connected. Checking interface IP..."
+          ifconfig tun0 || { echo "Interface tun0 not found"; exit 1; }
 
       - name: Test Server Connection
         run: |
